---
- name: Install Node Exporter
  hosts: all
  become: true
  vars_files:
    - defaults/main.yml  # Load variables from vars/main.yml
  tasks:
    - name: Download Node Exporter
      get_url:
        url: "{{ node_exporter_url }}"
        dest: "/tmp/node_exporter.tar.gz"

    - name: Create installation directory
      file:
        path: "{{ node_exporter_install_dir }}"
        state: directory
        mode: '0755'

    - name: Extract Node Exporter
      unarchive:
        src: "/tmp/node_exporter.tar.gz"
        dest: "{{ node_exporter_install_dir }}"
        remote_src: yes
        extra_opts: ["--strip-components=1"]

    - name: Move Node Exporter binary
      command: mv "{{ node_exporter_install_dir }}/node_exporter" "{{ node_exporter_bin_path }}"

    - name: Copy Node Exporter systemd service file
      template:
        src: node_exporter.service.j2
        dest: "{{ node_exporter_service_path }}"

    - name: Reload systemd daemon
      systemd:
        daemon_reload: yes

    - name: Enable and Start Node Exporter service
      systemd:
        name: node_exporter
        enabled: yes
        state: started
