---
- name: Install Node Exporter
  hosts: all
  become: true
  tasks:
    - name: Download Node Exporter
      get_url:
        url: "https://github.com/prometheus/node_exporter/releases/latest/download/node_exporter-1.7.0.linux-amd64.tar.gz"
        dest: "/tmp/node_exporter.tar.gz"

    - name: Create installation directory
      file:
        path: "/opt/node_exporter"
        state: directory
        mode: '0755'

    - name: Extract Node Exporter
      unarchive:
        src: "/tmp/node_exporter.tar.gz"
        dest: "/opt/node_exporter"
        remote_src: yes
        extra_opts: ["--strip-components=1"]

    - name: Move Node Exporter binary
      copy:
        src: "/opt/node_exporter/node_exporter"
        dest: "/usr/local/bin/node_exporter"
        mode: '0755'
        remote_src: yes

    - name: Copy Node Exporter systemd service file
      template:
        src: node_exporter.service.j2
        dest: /etc/systemd/system/node_exporter.service

    - name: Reload systemd daemon
      systemd:
        daemon_reload: yes

    - name: Enable and Start Node Exporter service
      systemd:
        name: node_exporter
        enabled: yes
        state: started
