---
- name: Get Instance ID
  shell: "curl -s http://169.254.169.254/latest/meta-data/instance-id"
  register: instance_id
  changed_when: false

- name: Add Monitoring tag to EC2
  amazon.aws.ec2_tag:
    region: "eu-north-1"
    resource: "{{ instance_id.stdout }}"
    tags:
      Monitoring: "enabled"
